version: "3"
services:
  mb_projects_laravel:
    image: mariadb:10.1.48-bionic
    container_name: mb_projects_laravel
    volumes:
      - "/home/dana-maria/bootcampDev/www/event_management/laravel/docker-containers/db:/var/www/html"
    ports:
      - "33102:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    networks:
      - project-network
    restart: unless-stopped

  it-academy-project_laravel:
    image: amoraresco/it-academy-project:latest
    container_name: it-academy-project_laravel
    links:
      - mb_projects_laravel
      - project-redis
    ports:
      - "89:80"
      - "8823:22"
    working_dir: /var/www/html
    volumes:
      - "/home/dana-maria/bootcampDev/www/event_management/laravel:/var/www/html"
    environment:
      - APP_URL=http://myproject.com
      - MAIL_HOST=project-mailhog
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=danamaria.cozaru@gmail.com
      - MAIL_NAME="PHR API"
      - MAIL_DELAY=2500
      - DB_HOST=mb_projects_laravel
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=test
      - DB_PORT=3306
    networks:
      - project-network
    restart: unless-stopped

# /*
#     sudo docker run --name it-academy-project_laravel -d \
#     -p 89:80 \
#     -p 8823:22 \
#     --restart unless-stopped \
#     --volume /home/dana-maria/bootcampDev/www/event_management/laravel:/var/www/html \
#    --network=laravel_network \
#     amoraresco/it-academy-project:latest \
# */

  project-mailhog:
    image: mailhog/mailhog
    container_name: project-mailhogs
    ports:
      - "8825:8025"
      - "8125:1025"
    networks:
      - project-network

  project-redis:
    image: redis:3.0
    container_name: project-rediss
    volumes:
      - "/home/containers/project/docker-compose/redis/cache/data:/data"
    ports:
      - "8379:6379"
    restart: unless-stopped
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
